// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview An AI agent that suggests ad copy based on an image of an outdoor location.
 *
 * - suggestAdCopy - A function that handles the ad copy suggestion process.
 * - SuggestAdCopyInput - The input type for the suggestAdCopy function.
 * - SuggestAdCopyOutput - The return type for the suggestAdCopy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestAdCopyInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the outdoor location, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type SuggestAdCopyInput = z.infer<typeof SuggestAdCopyInputSchema>;

const SuggestAdCopyOutputSchema = z.object({
  adCopySuggestions: z
    .array(z.string())
    .describe('An array of suggested ad copy options.'),
});
export type SuggestAdCopyOutput = z.infer<typeof SuggestAdCopyOutputSchema>;

export async function suggestAdCopy(input: SuggestAdCopyInput): Promise<SuggestAdCopyOutput> {
  return suggestAdCopyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestAdCopyPrompt',
  input: {schema: SuggestAdCopyInputSchema},
  output: {schema: SuggestAdCopyOutputSchema},
  prompt: `You are an expert advertising copywriter specializing in outdoor advertisements. Based on the image of the location provided, suggest 3 concise and creative ad copy options that are appropriate for the location.

Location Image: {{media url=photoDataUri}}

Ensure the suggestions are location-appropriate and can capture attention quickly. Return the ad copy options as an array.

Here are the suggested ad copy options:`,
});

const suggestAdCopyFlow = ai.defineFlow(
  {
    name: 'suggestAdCopyFlow',
    inputSchema: SuggestAdCopyInputSchema,
    outputSchema: SuggestAdCopyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
